import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  generateCodebaseGuide,
  guideStatus,
  initCodebaseGuide,
  refreshCodebaseGuide,
  GUIDE_NOTES_HEADING,
} from '../src/lib/codebase-guide.js';
import type { RepoScan } from '../src/lib/repo-scan.js';

/**
 * CODEBASE_GUIDE.md is the SpyCode-GENERATED architecture doc for the END-USER's
 * repo. `generateCodebaseGuide` is pure (a RepoScan in → a string out), so the
 * shape tests use a fabricated scan; the write helpers run entirely inside a
 * throwaway temp dir — NEVER the CLI's own project root or docs/.
 */

const made: string[] = [];

function tempProject(pkg?: Record<string, unknown>): string {
  const dir = mkdtempSync(join(tmpdir(), 'spycode-guide-'));
  made.push(dir);
  mkdirSync(join(dir, '.git'), { recursive: true });
  if (pkg) writeFileSync(join(dir, 'package.json'), JSON.stringify(pkg), 'utf8');
  return dir;
}

afterEach(() => {
  for (const d of made.splice(0)) rmSync(d, { recursive: true, force: true });
});

/** A representative scan with every field the generator consumes. */
function fakeScan(over: Partial<RepoScan> = {}): RepoScan {
  return {
    cwd: '/fake',
    topDirs: ['src/', 'tests/', 'docs/'],
    topFiles: ['package.json', 'README.md'],
    languages: [{ lang: 'TypeScript', count: 42 }],
    fileCount: 50,
    sampled: false,
    keyFiles: ['package.json', 'README.md', 'tsconfig.json'],
    pkg: {
      name: 'fixture-app',
      description: 'A fixture project used in tests.',
      scripts: ['build', 'test', 'lint', 'cook'],
      main: './build/index.js',
      bin: ['fixture'],
      exports: ['.', './sub'],
      dependencies: ['react', 'commander'],
      devDependencies: ['vitest', 'typescript'],
    },
    readmeSummary: 'Readme overview sentence.',
    entryFiles: ['src/index.ts'],
    ...over,
  };
}

describe('generateCodebaseGuide — sections', () => {
  test('emits the full set of expected sections + the SpyCore header', () => {
    const out = generateCodebaseGuide(fakeScan());
    expect(out).toContain('# fixture-app — Codebase Guide');
    expect(out).toContain('Generated by SpyCore — a living architecture reference');
    expect(out).toContain('## Overview');
    expect(out).toContain('## Run, build & test');
    expect(out).toContain('## Architecture map');
    expect(out).toContain('## Key entry points');
    expect(out).toContain('## Major dependencies');
    expect(out).toContain('## Data flow & module relationships');
    expect(out).toContain('## Conventions');
    expect(out).toContain('## Gotchas');
    expect(out).toContain(GUIDE_NOTES_HEADING);
  });

  test('Overview uses package.json description, then README, then a placeholder', () => {
    expect(generateCodebaseGuide(fakeScan())).toContain('A fixture project used in tests.');

    const noDesc = fakeScan({
      pkg: { name: 'x', scripts: [], dependencies: [], devDependencies: [] },
      readmeSummary: 'Readme overview sentence.',
    });
    const out2 = generateCodebaseGuide(noDesc);
    expect(out2).toContain('Readme overview sentence.');

    const nothing = fakeScan({ pkg: undefined, readmeSummary: undefined });
    expect(generateCodebaseGuide(nothing)).toContain('No description found in package.json or README');
  });

  test('Run/build/test rows derive from package.json scripts', () => {
    const out = generateCodebaseGuide(fakeScan());
    expect(out).toContain('`npm run build`');
    expect(out).toContain('`npm run test`');
    expect(out).toContain('`npm run lint`');
    // Non-preferred scripts are listed under "Other scripts".
    expect(out).toContain('Other scripts:');
    expect(out).toContain('`cook`');
  });

  test('Architecture map infers purpose for known dirs and flags unknown ones', () => {
    const out = generateCodebaseGuide(
      fakeScan({ topDirs: ['src/', 'tests/', 'weirdthing/'] }),
    );
    expect(out).toContain('| `src/` | Application / library source code |');
    expect(out).toContain('| `tests/` | Test suite |');
    expect(out).toContain('| `weirdthing/` | _purpose unclear — describe it_ |');
  });

  test('Key entry points surface main/bin/exports + detected source files', () => {
    const out = generateCodebaseGuide(fakeScan());
    expect(out).toContain('**main:** `./build/index.js`');
    expect(out).toContain('**bin:** `fixture`');
    expect(out).toContain('**exports:** `.`, `./sub`');
    expect(out).toContain('**Source entry files:** `src/index.ts`');
  });

  test('Major dependencies list runtime + dev names (no scrub of the user deps)', () => {
    const out = generateCodebaseGuide(fakeScan());
    expect(out).toContain('**Runtime (2):**');
    expect(out).toContain('`react`');
    expect(out).toContain('`commander`');
    expect(out).toContain('**Dev (2):**');
    expect(out).toContain('`vitest`');
    expect(out).toContain('`typescript`');
  });

  test('Data flow stays honest — says "high-level" when nothing is inferable', () => {
    const inferable = generateCodebaseGuide(
      fakeScan({ topDirs: ['apps/', 'packages/', 'server/', 'client/'] }),
    );
    expect(inferable).toContain('Monorepo layout');
    expect(inferable).toContain('Split client/server');
    expect(inferable).toContain('high-level inference');

    const bare = generateCodebaseGuide(fakeScan({ topDirs: ['whatever/'] }));
    expect(bare).toContain('High-level only');
  });

  test('stays bounded: a huge repo trims the dir table and caps dep lists', () => {
    const manyDirs = Array.from({ length: 60 }, (_, i) => `dir${i}/`);
    const manyDeps = Array.from({ length: 100 }, (_, i) => `dep-${i}`);
    const out = generateCodebaseGuide(
      fakeScan({
        topDirs: manyDirs,
        pkg: {
          name: 'big',
          scripts: ['build'],
          dependencies: manyDeps,
          devDependencies: [],
        },
      }),
    );
    expect(out).toContain('more top-level directories (list trimmed)');
    expect(out).toContain('+60 more'); // 100 deps, capped at 40
    // A few hundred lines max even for a big repo.
    expect(out.split('\n').length).toBeLessThan(300);
  });

  test('static template is SpyCore-branded', () => {
    const clean = fakeScan({
      topDirs: ['src/', 'tests/'],
      pkg: {
        name: 'clean',
        description: 'Nothing vendor-y here.',
        scripts: ['build', 'test'],
        dependencies: ['react'],
        devDependencies: ['vitest'],
      },
      readmeSummary: undefined,
    });
    const out = generateCodebaseGuide(clean);
    expect(out).toContain('SpyCore');
    // The "no upstream vendor names" guarantee (with its vendor literals) lives
    // in the manifest-excluded negative gate (tests/identity-denylist.test.ts)
    // so this shipping file carries no upstream-vendor strings.
  });
});

describe('initCodebaseGuide — /init half', () => {
  test('creates CODEBASE_GUIDE.md from a real scan when none exists', async () => {
    const dir = tempProject({
      name: 'realproj',
      description: 'A real temp project.',
      scripts: { build: 'tsc', test: 'vitest' },
      dependencies: { commander: '^11.0.0' },
      devDependencies: { typescript: '^5.0.0' },
    });
    mkdirSync(join(dir, 'src'), { recursive: true });
    writeFileSync(join(dir, 'src', 'index.ts'), 'export {};', 'utf8');
    writeFileSync(join(dir, 'README.md'), '# realproj\n\nFrom the readme.\n', 'utf8');

    const res = await initCodebaseGuide(dir);
    expect(res.created).toBe(true);
    expect(existsSync(res.path)).toBe(true);

    const content = readFileSync(res.path, 'utf8');
    // End-to-end the EXTENDED scanner fed the generator: deps, entry file, scripts.
    expect(content).toContain('# realproj — Codebase Guide');
    expect(content).toContain('A real temp project.');
    expect(content).toContain('`npm run build`');
    expect(content).toContain('**Source entry files:** `src/index.ts`');
    expect(content).toContain('`commander`');
    expect(content).toContain('`typescript`');
  });

  test('refuses to overwrite an existing CODEBASE_GUIDE.md', async () => {
    const dir = tempProject({ name: 'x' });
    writeFileSync(join(dir, 'CODEBASE_GUIDE.md'), 'HAND WRITTEN — DO NOT CLOBBER', 'utf8');
    const res = await initCodebaseGuide(dir);
    expect(res.created).toBe(false);
    expect(readFileSync(res.path, 'utf8')).toBe('HAND WRITTEN — DO NOT CLOBBER');
  });
});

describe('refreshCodebaseGuide — /guide refresh', () => {
  test('overwrites the generated body on refresh', async () => {
    const dir = tempProject({ name: 'refreshme', scripts: { build: 'x' } });
    writeFileSync(join(dir, 'CODEBASE_GUIDE.md'), '# stale title\n\nstale body\n', 'utf8');
    const res = await refreshCodebaseGuide(dir);
    expect(res.existed).toBe(true);
    expect(res.preservedNotes).toBe(false);
    const content = readFileSync(res.path, 'utf8');
    expect(content).toContain('# refreshme — Codebase Guide');
    expect(content).not.toContain('stale title');
    expect(content).not.toContain('stale body');
  });

  test('creates the file when none exists yet', async () => {
    const dir = tempProject({ name: 'fresh' });
    const res = await refreshCodebaseGuide(dir);
    expect(res.existed).toBe(false);
    expect(existsSync(res.path)).toBe(true);
  });

  test('preserves a hand-written "## Notes (manual)" section across refresh', async () => {
    const dir = tempProject({ name: 'noted', scripts: { build: 'x' } });
    const handEdited = [
      '# whatever',
      '',
      '## Notes (manual)',
      '',
      '- A durable note that must survive refresh.',
      '',
    ].join('\n');
    writeFileSync(join(dir, 'CODEBASE_GUIDE.md'), handEdited, 'utf8');

    const res = await refreshCodebaseGuide(dir);
    expect(res.preservedNotes).toBe(true);
    const content = readFileSync(res.path, 'utf8');
    // Body regenerated…
    expect(content).toContain('# noted — Codebase Guide');
    // …but the manual note carried across.
    expect(content).toContain('- A durable note that must survive refresh.');
  });

  test('a Notes section with only boilerplate is NOT treated as user content', async () => {
    // A freshly generated file has an empty Notes section; refreshing it again
    // must not report a preserved note.
    const dir = tempProject({ name: 'empty-notes' });
    await initCodebaseGuide(dir);
    const res = await refreshCodebaseGuide(dir);
    expect(res.existed).toBe(true);
    expect(res.preservedNotes).toBe(false);
  });
});

describe('guideStatus — /guide (no arg)', () => {
  test('reports absence in a fresh project', () => {
    const dir = tempProject({ name: 'none' });
    const status = guideStatus(dir);
    expect(status.exists).toBe(false);
    expect(status.lines).toBe(0);
    expect(status.path).toBe(join(dir, 'CODEBASE_GUIDE.md'));
  });

  test('reports presence + a line count once generated', async () => {
    const dir = tempProject({ name: 'present', scripts: { build: 'x' } });
    await initCodebaseGuide(dir);
    const status = guideStatus(dir);
    expect(status.exists).toBe(true);
    expect(status.lines).toBeGreaterThan(20);
  });
});
