import { describe, expect, test, vi } from 'vitest';
import {
  buildBranchPrompt,
  buildCommitPrompt,
  buildPrPrompt,
  GIT_DIFF_MAX_CHARS,
  reviewLoop,
  sanitizeBranchName,
  splitTitleBody,
  stripGenerationArtifacts,
  TRUNCATION_MARKER,
  truncateWithMarker,
} from '../src/lib/git-generate.js';
import { WIRE_MESSAGE_MAX_CHARS } from '../src/lib/attachments.js';

/**
 * PHASE-1 1.5 - unit tests for the git-generation core: prompt assembly
 * under the 1.2 wire budget, the non-configurable attribution-trailer net,
 * branch-name sanitizing, and the accept/edit/regenerate/cancel state
 * machine.
 */

describe('truncateWithMarker', () => {
  test('short text passes through untouched', () => {
    expect(truncateWithMarker('abc', 100)).toBe('abc');
  });

  test('over-budget text is cut WITH the explicit marker, inside the cap', () => {
    const out = truncateWithMarker('x'.repeat(30_000), 24_000);
    expect(out.endsWith(TRUNCATION_MARKER)).toBe(true);
    expect(out.length).toBeLessThanOrEqual(24_000);
  });
});

describe('prompt assembly', () => {
  test('commit prompt carries the staged diff, file list, and style log', () => {
    const p = buildCommitPrompt({
      stat: ' src/a.ts | 2 +-',
      diff: 'diff --git a/src/a.ts b/src/a.ts\n+hello',
      recentLog: 'abc123 feat: prior work',
    });
    expect(p).toContain('+hello');
    expect(p).toContain('src/a.ts | 2 +-');
    expect(p).toContain('feat: prior work');
    expect(p).toContain('Conventional Commits');
    expect(p).toContain('at most 72 characters');
  });

  test('the no-trailer instruction is pinned in every prompt', () => {
    const commit = buildCommitPrompt({ stat: '', diff: 'd', recentLog: '' });
    const pr = buildPrPrompt({ base: 'main', branch: 'f', log: 'l', diff: 'd' });
    const branch = buildBranchPrompt({ hint: 'h', diff: 'd' });
    for (const p of [commit, pr, branch]) {
      expect(p).toMatch(/Never add a trailer/);
      expect(p).toMatch(/Co-Authored-By/);
      expect(p).toMatch(/Generated with/);
    }
  });

  test('oversized diff is truncated at the block budget with the marker', () => {
    const p = buildCommitPrompt({
      stat: '',
      diff: 'y'.repeat(GIT_DIFF_MAX_CHARS + 5_000),
      recentLog: '',
    });
    expect(p).toContain(TRUNCATION_MARKER);
    expect(p.length).toBeLessThanOrEqual(WIRE_MESSAGE_MAX_CHARS);
  });

  test('pathological inputs still fit the assembled wire cap', () => {
    const p = buildCommitPrompt({
      stat: 's'.repeat(100_000),
      diff: 'd'.repeat(100_000),
      recentLog: 'l'.repeat(50_000),
    });
    expect(p.length).toBeLessThanOrEqual(WIRE_MESSAGE_MAX_CHARS);
    const pr = buildPrPrompt({
      base: 'main',
      branch: 'feat/x',
      log: 'l'.repeat(50_000),
      diff: 'd'.repeat(100_000),
    });
    expect(pr.length).toBeLessThanOrEqual(WIRE_MESSAGE_MAX_CHARS);
  });

  test('branch prompt with no diff says so instead of an empty block', () => {
    const p = buildBranchPrompt({ hint: 'add rate limiting', diff: '   ' });
    expect(p).toContain('add rate limiting');
    expect(p).toContain('no diff');
  });
});

describe('stripGenerationArtifacts - the trailer net', () => {
  test('strips Co-Authored-By even when the model ignores the instruction', () => {
    const out = stripGenerationArtifacts(
      'feat: add auth\n\nAdds the login flow.\n\nCo-Authored-By: Some Bot <bot@example.com>',
    );
    expect(out).toBe('feat: add auth\n\nAdds the login flow.');
    expect(out.toLowerCase()).not.toContain('co-authored-by');
  });

  test('strips Generated-with / generated-by / robot-emoji footer lines', () => {
    const out = stripGenerationArtifacts(
      'fix: close leak\n\nGenerated with SomeTool\ngenerated by an assistant\n🤖 footer',
    );
    expect(out).toBe('fix: close leak');
  });

  test('unwraps a single full-message code fence', () => {
    expect(stripGenerationArtifacts('```\nfeat: fenced\n```')).toBe('feat: fenced');
    expect(stripGenerationArtifacts('```text\nfeat: tagged fence\n```')).toBe(
      'feat: tagged fence',
    );
  });

  test('strips C0 control characters but keeps newlines and tabs', () => {
    const out = stripGenerationArtifacts('feat: a\u001b[31mred\u001b[0m\n\tbody');
    expect(out).toBe('feat: a[31mred[0m\n\tbody');
  });

  test('a normal message passes through unchanged', () => {
    const msg = 'refactor(core): split parser\n\nKeeps each stage testable.';
    expect(stripGenerationArtifacts(msg)).toBe(msg);
  });
});

describe('splitTitleBody', () => {
  test('first line is the title, rest is the body', () => {
    const { title, body } = splitTitleBody('feat: add x\n\nLine one.\nLine two.');
    expect(title).toBe('feat: add x');
    expect(body).toBe('Line one.\nLine two.');
  });

  test('title-only text yields an empty body', () => {
    const { title, body } = splitTitleBody('fix: only title');
    expect(title).toBe('fix: only title');
    expect(body).toBe('');
  });
});

describe('sanitizeBranchName', () => {
  test('kebab-cases and lowercases model output', () => {
    expect(sanitizeBranchName('Feat/Add User AUTH!!')).toBe('feat/add-user-auth');
  });

  test('collapses extra slashes to one type separator', () => {
    expect(sanitizeBranchName('feat/add/user/auth')).toBe('feat/add-user-auth');
  });

  test('clamps to 60 chars without a dangling separator', () => {
    const name = sanitizeBranchName(`feat/${'very-'.repeat(20)}long`);
    expect(name.length).toBeLessThanOrEqual(60);
    expect(name).not.toMatch(/[-/]$/);
  });

  test('takes only the first non-empty line and drops backticks', () => {
    expect(sanitizeBranchName('\n`fix/null-check`\nsecond line')).toBe('fix/null-check');
  });
});

describe('reviewLoop state machine', () => {
  function io(answers: string[], edits: string[] = [], regens: string[] = []) {
    const presented: string[] = [];
    const ask = vi.fn(async () => answers.shift() ?? 'c');
    const readEdit = vi.fn(async () => edits.shift() ?? '');
    const regenerate = vi.fn(async () => regens.shift() ?? 'regen');
    return {
      presented,
      ask,
      readEdit,
      regenerate,
      io: {
        present: (t: string) => void presented.push(t),
        ask,
        readEdit,
        regenerate,
      },
    };
  }

  test('accept returns the current text', async () => {
    const h = io(['a']);
    const r = await reviewLoop('feat: one', h.io);
    expect(r).toEqual({ action: 'accept', text: 'feat: one' });
    expect(h.presented).toEqual(['feat: one']);
  });

  test('cancel never mutates the text', async () => {
    const h = io(['c']);
    const r = await reviewLoop('feat: one', h.io);
    expect(r.action).toBe('cancel');
    expect(r.text).toBe('feat: one');
  });

  test('edit replaces the candidate, then accept commits the EDIT', async () => {
    const h = io(['e', 'a'], ['fix: edited subject']);
    const r = await reviewLoop('feat: original', h.io);
    expect(r).toEqual({ action: 'accept', text: 'fix: edited subject' });
    expect(h.presented).toEqual(['feat: original', 'fix: edited subject']);
  });

  test('an edited (pasted) message still passes the trailer net', async () => {
    const h = io(['e', 'a'], ['fix: pasted\n\nCo-Authored-By: Bot <b@x>']);
    const r = await reviewLoop('feat: original', h.io);
    expect(r.text).toBe('fix: pasted');
  });

  test('regenerate swaps in the fresh candidate', async () => {
    const h = io(['r', 'a'], [], ['feat: second try']);
    const r = await reviewLoop('feat: first', h.io);
    expect(r.text).toBe('feat: second try');
    expect(h.regenerate).toHaveBeenCalledTimes(1);
  });

  test('unrecognized input re-presents and re-asks', async () => {
    const h = io(['??', 'a']);
    const r = await reviewLoop('feat: one', h.io);
    expect(r.action).toBe('accept');
    expect(h.ask).toHaveBeenCalledTimes(2);
    expect(h.presented).toHaveLength(2);
  });

  test('an empty edit keeps the previous candidate', async () => {
    const h = io(['e', 'a'], ['   ']);
    const r = await reviewLoop('feat: keep me', h.io);
    expect(r.text).toBe('feat: keep me');
  });
});
