import { COMMAND_SPEC, type CommandSpec } from './spec.js';

/**
 * Bash completion generator.
 *
 * Strategy: emit a static script that walks dotted-path lookup tables at
 * completion time. Tables are baked in at generation time so completion never
 * spawns spycore — Tab stays fast and there's no surprise of executing a CLI
 * binary just to get a list of flags.
 *
 * Output uses Bash 3.2+ syntax (case statements, no associative arrays) so it
 * works on macOS system bash without requiring bash-completion@2.
 */
export function generateBashCompletion(): string {
  const subTable: string[] = [];
  const optTable: string[] = [];
  const valueTable: string[] = [];

  const visit = (cmd: CommandSpec, path: string[]): void => {
    const key = path.length === 0 ? '__root__' : path.join('.');
    const subs = (cmd.subcommands ?? []).map((s) => s.name).join(' ');
    const opts: string[] = [];
    for (const opt of cmd.options ?? []) {
      opts.push(opt.name);
      if (opt.short) opts.push(opt.short);
    }
    subTable.push(`    "${key}") echo "${subs}" ;;`);
    optTable.push(`    "${key}") echo "${opts.join(' ')}" ;;`);
    for (const opt of cmd.options ?? []) {
      if (opt.takesValue && opt.values && opt.values.length > 0) {
        const flagKeys = [opt.name, ...(opt.short ? [opt.short] : [])];
        for (const flagKey of flagKeys) {
          valueTable.push(
            `    "${key}::${flagKey}") echo "${opt.values.join(' ')}" ;;`,
          );
        }
      }
    }
    for (const sub of cmd.subcommands ?? []) {
      visit(sub, [...path, sub.name]);
    }
  };
  visit(COMMAND_SPEC, []);

  return `#!/usr/bin/env bash
# spycore — bash tab completion
#
# Install:
#   eval "$(spycore completion bash)"
# Or save to /etc/bash_completion.d/spycore (root) or ~/.bash_completion.d/spycore.
#
# Generated by 'spycore completion bash' — do not edit by hand. Re-run after
# upgrading the CLI to pick up new commands.

_spycore_subs_for() {
  case "$1" in
${subTable.join('\n')}
    *) echo "" ;;
  esac
}

_spycore_opts_for() {
  case "$1" in
${optTable.join('\n')}
    *) echo "" ;;
  esac
}

_spycore_values_for() {
  case "$1" in
${valueTable.join('\n')}
    *) echo "" ;;
  esac
}

_spycore() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  # Walk forward through non-flag words to find the deepest matched path.
  local path=""
  local i=1
  while [ $i -lt $COMP_CWORD ]; do
    local word="\${COMP_WORDS[$i]}"
    case "$word" in
      -*) i=$((i+1)); continue ;;
    esac
    local probe
    if [ -z "$path" ]; then
      probe="$word"
    else
      probe="$path.$word"
    fi
    local children
    if [ -z "$path" ]; then
      children=$(_spycore_subs_for "__root__")
    else
      children=$(_spycore_subs_for "$path")
    fi
    case " $children " in
      *" $word "*) path="$probe" ;;
      *) break ;;
    esac
    i=$((i+1))
  done

  local key="$path"
  if [ -z "$key" ]; then key="__root__"; fi

  # Option-value completion: previous token is a value-taking flag.
  if [[ "$prev" == -* ]]; then
    local values
    values=$(_spycore_values_for "$key::$prev")
    if [ -n "$values" ]; then
      COMPREPLY=( $(compgen -W "$values" -- "$cur") )
      return 0
    fi
  fi

  # Flag completion when the user is typing a flag.
  if [[ "$cur" == -* ]]; then
    local opts
    opts=$(_spycore_opts_for "$key")
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return 0
  fi

  # Subcommand completion at the current path.
  local subs
  subs=$(_spycore_subs_for "$key")
  if [ -n "$subs" ]; then
    COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    return 0
  fi

  # Fallback: file completion for positional args.
  COMPREPLY=( $(compgen -f -- "$cur") )
  return 0
}

complete -F _spycore spycore
`;
}

/** Summary used by tests / help output. */
export function summarizeBashCompletion(): {
  totalCommands: number;
  totalOptions: number;
} {
  let totalCommands = 0;
  let totalOptions = 0;
  const visit = (cmd: CommandSpec): void => {
    totalCommands += 1;
    totalOptions += (cmd.options ?? []).length;
    for (const sub of cmd.subcommands ?? []) visit(sub);
  };
  visit(COMMAND_SPEC);
  return { totalCommands, totalOptions };
}
