import { COMMAND_SPEC, type CommandSpec, type OptionSpec } from './spec.js';

/**
 * Fish completion generator.
 *
 * Fish uses a flat list of `complete -c <cmd>` directives, each scoped by
 * conditional functions like `__fish_use_subcommand` and
 * `__fish_seen_subcommand_from`. We emit one line per (subcommand path,
 * option) pair — fish handles the scoping at completion time.
 *
 * Install: `spycore completion fish > ~/.config/fish/completions/spycore.fish`.
 * Fish picks it up automatically; no `source` needed.
 */
export function generateFishCompletion(): string {
  const lines: string[] = [
    '# spycore — fish tab completion',
    '#',
    '# Install:',
    '#   spycore completion fish > ~/.config/fish/completions/spycore.fish',
    '#',
    '# Generated by `spycore completion fish` — do not edit by hand.',
    '',
    '# Disable file completion by default; individual entries opt back in.',
    'complete -c spycore -f',
    '',
  ];

  // Top-level options
  for (const opt of COMMAND_SPEC.options ?? []) {
    lines.push(formatOption('', opt));
  }
  lines.push('');

  // Top-level subcommands — only valid when the user hasn't typed one yet.
  for (const sub of COMMAND_SPEC.subcommands ?? []) {
    lines.push(
      `complete -c spycore -n '__fish_use_subcommand' -a '${sub.name}' -d '${escape(sub.description)}'`,
    );
  }
  lines.push('');

  // Walk all nested commands and emit per-command directives.
  const visit = (cmd: CommandSpec, path: string[]): void => {
    if (path.length === 0) return; // root already handled

    const condition = buildSeenCondition(path);

    // Subcommands of this node — but only if this is the deepest matched path.
    if (cmd.subcommands && cmd.subcommands.length > 0) {
      // No deeper subcommand selected yet.
      const noChildSelected = `${condition}; and not __fish_seen_subcommand_from ${cmd.subcommands
        .map((s) => s.name)
        .join(' ')}`;
      for (const sub of cmd.subcommands) {
        lines.push(
          `complete -c spycore -n '${noChildSelected}' -a '${sub.name}' -d '${escape(sub.description)}'`,
        );
      }
    }

    // Options for this command.
    for (const opt of cmd.options ?? []) {
      lines.push(formatOption(condition, opt));
    }

    // Files for commands that take positional args (and have no children).
    if (cmd.takesArgs && (cmd.subcommands ?? []).length === 0) {
      lines.push(`complete -c spycore -n '${condition}' -F`);
    }

    for (const sub of cmd.subcommands ?? []) {
      visit(sub, [...path, sub.name]);
    }
  };

  for (const sub of COMMAND_SPEC.subcommands ?? []) visit(sub, [sub.name]);

  return lines.join('\n');
}

function buildSeenCondition(path: string[]): string {
  // Each element of path must be "seen" in order. Fish's
  // __fish_seen_subcommand_from is unordered, but combined with a chain
  // it's a good-enough approximation for our flat command tree.
  return path
    .map((segment) => `__fish_seen_subcommand_from ${segment}`)
    .join('; and ');
}

function formatOption(condition: string, opt: OptionSpec): string {
  const longName = opt.name.replace(/^--/, '');
  const shortName = opt.short?.replace(/^-/, '');
  const desc = escape(opt.description ?? '');
  const flagPart = shortName ? `-s ${shortName} -l ${longName}` : `-l ${longName}`;
  const valuePart = opt.takesValue
    ? opt.values && opt.values.length > 0
      ? ` -x -a '${opt.values.join(' ')}'`
      : ' -r'
    : '';
  const condPart = condition ? ` -n '${condition}'` : '';
  return `complete -c spycore${condPart} ${flagPart}${valuePart} -d '${desc}'`;
}

function escape(s: string): string {
  // Fish single-quoted strings only need to escape single quotes and backslashes.
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
