import { COMMAND_SPEC, type CommandSpec } from './spec.js';

/**
 * PowerShell tab completion generator.
 *
 * Uses Register-ArgumentCompleter with a scriptblock. We bake the subcommand
 * tree, options, and value choices into the script as PowerShell hashtables
 * so completion runs without spawning spycore.
 *
 * Install:
 *   spycore completion powershell >> $PROFILE
 *   . $PROFILE  # to load it in the current session
 */
export function generatePowerShellCompletion(): string {
  const subEntries: string[] = [];
  const optEntries: string[] = [];
  const valueEntries: string[] = [];

  const visit = (cmd: CommandSpec, path: string[]): void => {
    const key = path.length === 0 ? '__root__' : path.join('.');
    const subs = (cmd.subcommands ?? []).map((s) => s.name);
    const opts: string[] = [];
    for (const opt of cmd.options ?? []) {
      opts.push(opt.name);
      if (opt.short) opts.push(opt.short);
    }
    subEntries.push(`    '${key}' = @(${subs.map(quote).join(', ')})`);
    optEntries.push(`    '${key}' = @(${opts.map(quote).join(', ')})`);
    for (const opt of cmd.options ?? []) {
      if (opt.takesValue && opt.values && opt.values.length > 0) {
        const flagKeys = [opt.name, ...(opt.short ? [opt.short] : [])];
        for (const flagKey of flagKeys) {
          valueEntries.push(
            `    '${key}::${flagKey}' = @(${opt.values.map(quote).join(', ')})`,
          );
        }
      }
    }
    for (const sub of cmd.subcommands ?? []) visit(sub, [...path, sub.name]);
  };
  visit(COMMAND_SPEC, []);

  return `# spycore — PowerShell tab completion
#
# Install:
#   spycore completion powershell >> $PROFILE
#   . $PROFILE
#
# Generated by 'spycore completion powershell' — do not edit by hand.

$global:SpycoreCompletionSubs = @{
${subEntries.join('\n')}
}

$global:SpycoreCompletionOpts = @{
${optEntries.join('\n')}
}

$global:SpycoreCompletionValues = @{
${valueEntries.join('\n')}
}

Register-ArgumentCompleter -Native -CommandName spycore -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }
    # Drop the program name itself.
    if ($tokens.Count -gt 0) { $tokens = $tokens[1..($tokens.Count - 1)] }

    # Walk forward through non-flag tokens to find the deepest matched path.
    $path = ''
    $i = 0
    while ($i -lt $tokens.Count - 1) {
        $tok = $tokens[$i]
        if ($tok.StartsWith('-')) { $i++; continue }
        $childrenKey = if ($path -eq '') { '__root__' } else { $path }
        $children = $global:SpycoreCompletionSubs[$childrenKey]
        if ($null -eq $children -or $children -notcontains $tok) { break }
        $path = if ($path -eq '') { $tok } else { "$path.$tok" }
        $i++
    }

    $key = if ($path -eq '') { '__root__' } else { $path }

    # Option-value completion: previous token is a value-taking flag.
    $prev = if ($tokens.Count -ge 2) { $tokens[$tokens.Count - 2] } else { '' }
    if ($prev.StartsWith('-')) {
        $values = $global:SpycoreCompletionValues["$key::$prev"]
        if ($null -ne $values) {
            return $values |
                Where-Object { $_ -like "$wordToComplete*" } |
                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
        }
    }

    # Flag completion when the user is typing a flag.
    if ($wordToComplete.StartsWith('-')) {
        $opts = $global:SpycoreCompletionOpts[$key]
        if ($null -ne $opts) {
            return $opts |
                Where-Object { $_ -like "$wordToComplete*" } |
                ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_) }
        }
    }

    # Subcommand completion.
    $subs = $global:SpycoreCompletionSubs[$key]
    if ($null -ne $subs) {
        return $subs |
            Where-Object { $_ -like "$wordToComplete*" } |
            ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_) }
    }

    return @()
}
`;
}

function quote(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}
