import { COMMAND_SPEC, type CommandSpec, type OptionSpec } from './spec.js';

/**
 * Zsh completion generator.
 *
 * Output is a `#compdef spycore` script meant to live somewhere in $fpath
 * (e.g. /usr/local/share/zsh/site-functions/_spycore) or to be sourced via
 * `eval "$(spycore completion zsh)"` if the user has compinit configured.
 *
 * Implementation: one function per command (`_spycore_<dotted_path>`),
 * dispatched from a top-level `_spycore` entry point that walks the argv
 * just like the bash version does. We use `_describe` to surface
 * descriptions in the zsh completion menu — that's the main UX win over
 * the bash version.
 */
export function generateZshCompletion(): string {
  const lines: string[] = [
    '#compdef spycore',
    '#',
    '# spycore — zsh tab completion',
    '#',
    '# Install (one of):',
    '#   1. eval "$(spycore completion zsh)"   (in ~/.zshrc, after compinit)',
    '#   2. spycore completion zsh > "${fpath[1]}/_spycore" && rm -f ~/.zcompdump && compinit',
    '#',
    '# Generated by `spycore completion zsh` — do not edit by hand.',
    '',
  ];

  const fnName = (path: string[]): string =>
    path.length === 0
      ? '_spycore'
      : `_spycore_${path.join('_').replace(/[^a-zA-Z0-9_]/g, '_')}`;

  const visit = (cmd: CommandSpec, path: string[]): void => {
    const fn = fnName(path);
    const subs = cmd.subcommands ?? [];
    const opts = cmd.options ?? [];

    lines.push(`${fn}() {`);
    lines.push(`  local -a _spycore_args`);
    lines.push(`  local context state line`);

    // Build _arguments specs.
    const argSpecs: string[] = [];
    for (const opt of opts) {
      argSpecs.push(formatOptionSpec(opt));
    }

    if (subs.length > 0) {
      argSpecs.push(`'1: :->subcommand'`);
      argSpecs.push(`'*::arg:->args'`);
    } else if (cmd.takesArgs) {
      argSpecs.push(`'*::arg:_files'`);
    }

    lines.push(`  _arguments -C \\`);
    if (argSpecs.length > 0) {
      argSpecs.forEach((spec, i) => {
        const trailing = i === argSpecs.length - 1 ? '' : ' \\';
        lines.push(`    ${spec}${trailing}`);
      });
    } else {
      lines.push(`    && return 0`);
    }

    if (subs.length > 0) {
      lines.push(`  case $state in`);
      lines.push(`    subcommand)`);
      const subDesc = subs
        .map((s) => `'${s.name}:${escapeZshDescription(s.description)}'`)
        .join(' ');
      lines.push(`      local -a _spycore_subs`);
      lines.push(`      _spycore_subs=(${subDesc})`);
      lines.push(`      _describe 'subcommand' _spycore_subs`);
      lines.push(`      ;;`);
      lines.push(`    args)`);
      lines.push(`      case $words[1] in`);
      for (const sub of subs) {
        const childFn = fnName([...path, sub.name]);
        lines.push(`        ${sub.name}) ${childFn} ;;`);
      }
      lines.push(`      esac`);
      lines.push(`      ;;`);
      lines.push(`  esac`);
    }
    lines.push('}');
    lines.push('');

    for (const sub of subs) visit(sub, [...path, sub.name]);
  };

  visit(COMMAND_SPEC, []);

  lines.push('_spycore "$@"');
  return lines.join('\n');
}

function formatOptionSpec(opt: OptionSpec): string {
  const desc = escapeZshDescription(opt.description ?? '');
  const flags = opt.short ? `{${opt.short},${opt.name}}` : opt.name;
  if (opt.takesValue) {
    if (opt.values && opt.values.length > 0) {
      const valueList = opt.values.join(' ');
      return `'${flags}[${desc}]:value:(${valueList})'`;
    }
    return `'${flags}[${desc}]:value:_files'`;
  }
  return `'${flags}[${desc}]'`;
}

function escapeZshDescription(s: string): string {
  return s.replace(/'/g, `'\\''`).replace(/\[/g, '\\[').replace(/\]/g, '\\]');
}
